// =============================================================================
// Resident bulk-import template — the .xlsx a PM downloads, fills, and
// uploads back to seed a property's resident roster in one shot.
//
// The file has TWO sheets so every export travels with its own guide:
//   Sheet 1 "Data"  — headers + a second "type" row (REQUIRED / OPTIONAL /
//                     IGNORED) so field roles are legible even in a viewer
//                     that ignores cell colors, plus a few example rows the
//                     PM can overwrite or delete.
//   Sheet 2 "Guide" — the mini-guide (import rules, validation, defaults,
//                     update-vs-add behavior).
//
// SheetJS's free build only ships partial cell-style support, so the Data
// sheet leans on a "type" text row (row 2) instead of colored cells.
// Everything the reader needs to import correctly is duplicated in words on
// Sheet 2, so nothing critical relies on formatting.
// =============================================================================

import * as XLSX from "xlsx";

// A field's role determines how validation treats it on import.
// - "system":   filled by us on export (e.g. property name) — ignored on read
// - "required": row is rejected if missing
// - "optional": passed through if present, ignored if blank
// - "ignored":  never read on import even if the user types something
const FIELDS = [
  { key: "email",        label: "Email",        role: "required", note: "Must match an existing resident account in Intervos." },
  { key: "unit_number",  label: "Unit number",  role: "optional", note: "Free text, e.g. 302, A-14, PH-2." },
  { key: "message",      label: "Welcome note", role: "optional", note: "Shown to the resident inside their in-app invite (max 500 chars)." },
];

const EXAMPLES = [
  { email: "alice@example.com", unit_number: "101",  message: "Welcome to the building!" },
  { email: "bob@example.com",   unit_number: "202",  message: "" },
  { email: "carla@example.com", unit_number: "",     message: "" },
];

// -----------------------------------------------------------------------------
// Sheet 1 — "Data". Headers on row 1, role tags on row 2, examples from row 3.
// -----------------------------------------------------------------------------
const buildDataSheet = () => {
  const headers = FIELDS.map((f) => f.label);
  const roles   = FIELDS.map((f) => f.role.toUpperCase());
  const rows    = EXAMPLES.map((e) => FIELDS.map((f) => e[f.key] ?? ""));

  const aoa = [headers, roles, ...rows];
  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // Column widths — approximate but keep it readable.
  ws["!cols"] = [
    { wch: 32 }, // email
    { wch: 16 }, // unit_number
    { wch: 48 }, // message
  ];

  return ws;
};

// -----------------------------------------------------------------------------
// Sheet 2 — "Guide". Plain text laid out row-by-row (arrays of strings). No
// styling. The order mirrors the InEight-style guide the user shared.
// -----------------------------------------------------------------------------
const buildGuideSheet = () => {
  const aoa = [
    ["Resident bulk import — guide"],
    [""],
    ["Legend (what each row-2 tag means)"],
    ["SYSTEM",   "Field generated by the system — leave blank, we fill it."],
    ["REQUIRED", "Field is required. Rows missing this value will be rejected."],
    ["OPTIONAL", "Field is optional. Leave blank if it doesn't apply."],
    ["IGNORED",  "Field is not read on import. Any value here is discarded."],
    [""],
    ["Import template rules"],
    ["• Column names in row 1 must not be changed."],
    ["• Do not remove or reorder columns."],
    ["• Row 2 (the role tags) is informational — you may leave it or delete it before importing."],
    ["• Every data row below row 2 will be processed."],
    [""],
    ["Validation & data rules"],
    ["• Email is required and must belong to an existing resident account in Intervos."],
    ["• Unit number is free text — anything the resident recognizes (e.g. 302, A-14, PH-2)."],
    ["• Welcome note is capped at 500 characters. Longer text is trimmed."],
    ["• Rows with a duplicate email (already invited or already on the property) are skipped, not rejected."],
    [""],
    ["Default values applied when blank"],
    ["Field", "Default"],
    ["Unit number",   "(none)"],
    ["Welcome note",  "(none)"],
    [""],
    ["Update / add behavior"],
    ["• If the email matches a resident already on this property, the row is skipped."],
    ["• If the email matches a resident who already has a pending invite to this property, the row is skipped."],
    ["• If the email matches a resident who is currently linked to a different property, the row is rejected."],
    ["• Otherwise, a fresh in-app invite is created and the resident is notified. Nothing is emailed."],
    [""],
    ["Field-by-field reference"],
    ["Field", "Role", "Description"],
    ...FIELDS.map((f) => [f.label, f.role.toUpperCase(), f.note]),
    [""],
    ["Tip: after import you'll see a per-row report — created, skipped, or errored. Fix any errored rows in the file and re-import; already-created rows will be skipped automatically."],
  ];

  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = [{ wch: 22 }, { wch: 14 }, { wch: 70 }];
  return ws;
};

// -----------------------------------------------------------------------------
// Public: build the workbook and return an xlsx Buffer ready to stream to the
// browser. Callers set the Content-Disposition + Content-Type headers.
// -----------------------------------------------------------------------------
export const buildResidentImportTemplate = () => {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, buildDataSheet(),  "Data");
  XLSX.utils.book_append_sheet(wb, buildGuideSheet(), "Guide");
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
};

// -----------------------------------------------------------------------------
// Public: parse an uploaded .xlsx/.xls/.csv buffer into normalized row objects.
//
// Contract:
//   - We only read the FIRST sheet in the workbook (matches InEight — Sheet 1
//     is always the data sheet, Sheet 2 is docs).
//   - Row 1 is treated as headers; matched case-insensitively against FIELDS.
//   - Row 2 (the "REQUIRED / OPTIONAL / IGNORED" role tags) is auto-detected
//     and skipped so PMs don't have to delete it before importing.
//   - Fully-empty rows are skipped silently.
//   - Returns { rows: [{ rowNumber, email, unit_number, message }], errors: [...] }
//     where errors are STRUCTURAL problems (missing column, unreadable file);
//     per-row validation happens in the controller.
// -----------------------------------------------------------------------------
export const parseResidentImportBuffer = (buffer) => {
  const errors = [];
  let wb;
  try {
    wb = XLSX.read(buffer, { type: "buffer" });
  } catch (err) {
    return { rows: [], errors: [{ message: `Could not read the file — is it a valid .xlsx? (${err.message})` }] };
  }

  const sheetName = wb.SheetNames[0];
  if (!sheetName) return { rows: [], errors: [{ message: "The workbook is empty." }] };
  const sheet = wb.Sheets[sheetName];

  // aoa with defval so blanks come through as "" instead of undefined.
  const aoa = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", blankrows: false });
  if (aoa.length === 0) return { rows: [], errors: [{ message: "The sheet has no rows." }] };

  const headers = aoa[0].map((h) => String(h || "").trim().toLowerCase());
  const findCol = (labelOrKey) => {
    const l = labelOrKey.toLowerCase();
    const idx = headers.findIndex((h) => h === l);
    return idx;
  };

  // Locate each field by its label OR key. Missing REQUIRED columns are hard
  // errors; missing OPTIONAL columns just mean we never try to read them.
  const colIndex = {};
  for (const f of FIELDS) {
    let idx = findCol(f.label);
    if (idx === -1) idx = findCol(f.key);
    colIndex[f.key] = idx;
    if (idx === -1 && f.role === "required") {
      errors.push({ message: `Missing required column: "${f.label}".` });
    }
  }
  if (errors.length) return { rows: [], errors };

  // Detect and skip row 2 if it's a role tag row (contains REQUIRED/OPTIONAL/
  // IGNORED/SYSTEM in the first non-empty cell). Otherwise treat row 2 as data.
  let dataStart = 1;
  if (aoa[1]) {
    const first = String(aoa[1][0] || "").trim().toUpperCase();
    if (["REQUIRED", "OPTIONAL", "IGNORED", "SYSTEM"].includes(first)) {
      dataStart = 2;
    }
  }

  const rows = [];
  for (let i = dataStart; i < aoa.length; i++) {
    const raw = aoa[i];
    const email       = String(raw[colIndex.email]       ?? "").trim().toLowerCase();
    const unit_number = String(raw[colIndex.unit_number] ?? "").trim();
    const message     = String(raw[colIndex.message]     ?? "").trim().slice(0, 500);

    // Skip empty rows so trailing whitespace in the sheet doesn't produce
    // "email required" errors on rows the PM didn't intend to submit.
    if (!email && !unit_number && !message) continue;

    rows.push({
      rowNumber: i + 1, // 1-indexed for humans; matches the row number in Excel
      email,
      unit_number: unit_number || null,
      message:     message     || null,
    });
  }

  return { rows, errors: [] };
};
